"""initial schema

Revision ID: a7480ad88b78
Revises:
Create Date: 2026-07-01 00:00:00

ponytail: hand-written, not generated by `alembic revision --autogenerate`,
because this sandbox has no network access to install alembic/sqlalchemy
and actually run it. Built by reading every model in
src/bot/database/models/ column-for-column against what create_all()
already produces at runtime (see database/session.py::create_db_and_tables).

Two details worth flagging explicitly:

1. None of the Enum columns pass `values_callable`, so SQLAlchemy's default
   applies: it persists each enum member's *name* (e.g. "EN", "ONE_WEEK",
   "WALLET_TOPUP"), not its *value* (e.g. "en", "1w", "wallet_topup"). This
   matches the existing models exactly and is not a mistake here.

2. `default=` on a model column is a Python/ORM-side default (applied by
   SQLAlchemy right before INSERT) and produces NO DDL. `server_default=`
   is an actual database-level DEFAULT clause. Most boolean/numeric columns
   here use only `default=`, so this migration deliberately does NOT add a
   server_default for them, to match create_all()'s DDL exactly — only the
   handful of `*_at` timestamp columns that use `server_default=func.now()`
   in the model get one here.

Before trusting this in production: run `alembic upgrade head` against a
throwaway database and diff the resulting schema against one built by
`create_db_and_tables()` (e.g. `sqlite3 a.db ".schema"` vs `sqlite3 b.db
".schema"` after each). This migration has been checked by hand against
every model file, not by executing it.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "a7480ad88b78"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── users ────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("language", sa.Enum("EN", "AM", name="userlanguage"), nullable=False),
        sa.Column("wallet_balance", sa.Float(), nullable=False),
        sa.Column("is_vip", sa.Boolean(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("last_active", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_users_telegram_id", "users", ["telegram_id"], unique=True)

    # ── movies ───────────────────────────────────────────────────────────────
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("file_id", sa.String(length=256), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ppv_price", sa.Float(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("is_broken", sa.Boolean(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_movies_file_id", "movies", ["file_id"], unique=True)
    op.create_index("ix_movies_title", "movies", ["title"], unique=False)

    # ── channels ─────────────────────────────────────────────────────────────
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=True, unique=True),
        sa.Column("category", sa.Enum("FREE", "VIP", name="channelcategory"), nullable=False),
        sa.Column("force_join", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    # ── promo_codes ──────────────────────────────────────────────────────────
    op.create_table(
        "promo_codes",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column(
            "code_type",
            sa.Enum("VIP_DAYS", "WALLET_CREDIT", name="promocodetype"),
            nullable=False,
        ),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_promo_codes_code", "promo_codes", ["code"], unique=True)

    # ── settings ─────────────────────────────────────────────────────────────
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), primary_key=True),
        sa.Column("value", sa.Text(), nullable=False),
    )

    # ── search_logs ──────────────────────────────────────────────────────────
    op.create_table(
        "search_logs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("query", sa.String(length=256), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Enum("MISS", "REQUEST", name="searchlogkind"), nullable=False),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_search_logs_query", "search_logs", ["query"], unique=False)

    # ── payments (FK -> users) ───────────────────────────────────────────────
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "gateway",
            sa.Enum("CHAPA", "BANK", "WALLET", name="paymentgateway"),
            nullable=False,
        ),
        sa.Column(
            "payment_type",
            sa.Enum("VIP", "WALLET_TOPUP", "PPV", name="paymenttype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", "EXPIRED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("reference", sa.String(length=256), nullable=True),
        sa.Column("receipt_file_id", sa.String(length=256), nullable=True),
        sa.Column("rejection_note", sa.Text(), nullable=True),
        sa.Column("plan", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )

    # ── subscriptions (FK -> users, payments) ───────────────────────────────
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "plan",
            sa.Enum(
                "ONE_WEEK", "TWO_WEEKS", "ONE_MONTH", "THREE_MONTHS",
                "SIX_MONTHS", "ONE_YEAR", "CUSTOM", "REFERRAL",
                name="planduration",
            ),
            nullable=False,
        ),
        sa.Column("custom_days", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payment_id", sa.Integer(), sa.ForeignKey("payments.id", ondelete="SET NULL"), nullable=True),
    )

    # ── referrals (FK -> users) ──────────────────────────────────────────────
    op.create_table(
        "referrals",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False, unique=True,
        ),
        sa.Column("referral_code", sa.String(length=32), nullable=False),
        sa.Column("invite_count", sa.Integer(), nullable=False),
        sa.Column("rewards_claimed", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_referrals_referral_code", "referrals", ["referral_code"], unique=True)

    # ── watchlist (FK -> users, movies) ──────────────────────────────────────
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("movie_id", sa.Integer(), sa.ForeignKey("movies.id", ondelete="CASCADE"), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("user_id", "movie_id", name="uq_watchlist_user_movie"),
    )


def downgrade() -> None:
    # Reverse dependency order.
    op.drop_table("watchlist")
    op.drop_table("referrals")
    op.drop_table("subscriptions")
    op.drop_table("payments")
    op.drop_table("search_logs")
    op.drop_table("settings")
    op.drop_table("promo_codes")
    op.drop_table("channels")
    op.drop_table("movies")
    op.drop_table("users")

    # Explicit type drops for Postgres (native ENUM types aren't removed by
    # drop_table alone). No-ops on SQLite, which never created these as
    # separate objects in the first place — inlined as VARCHAR + CHECK.
    bind = op.get_bind()
    for enum_name in (
        "userlanguage", "channelcategory", "promocodetype", "searchlogkind",
        "paymentgateway", "paymenttype", "paymentstatus", "planduration",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
